	
[debug]
address = "0.0.0.0"
port = 8000
secret_key = "/QYlQI3ZiTLfHLOT4i9ZLSRVB37snf8f5XbKuWAYZFo="

[release]

address = "0.0.0.0"
port = 8000
secret_key = "fZZJ9p8Blasg/Ge+OIKa0fHixBAZxRM4I3ujcTOfGjQ="